%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Generated by Tianyi Yang 051517. 
% Modified from GeneratePhaseMap v .1 Jan/11/2016 by Bill Green and James Corsetti
% This program generate one single phasemap from one measured "snap"-- interferogram measurements




% function [phasemap,timestamp] = PhaseMapfrommat(PSramp,htrans,vidobj,tag,pollrate)
function phasemap = PhaseMapfromsnap(snap)
    
%Malacara Algorithm to generate a phasmap Pg. 585 N-bucket algorithm
del = (1:size(snap,3)).*2.*pi./(size(snap,3)-1);
I = double(snap);%(:,:,1:PSramp);
N = 0;
D = 0;
for qrs = 1:(length(del))
    N = N - I(:,:,qrs).*sin(del(qrs));
    N=double(N);
    D = D + I(:,:,qrs).*cos(del(qrs));
    D=double(D);
end
phasemap = atan2(N,D);

end